spring:
  mail:
    password: NEED_TO_INPUT
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: c4c2cab3f249ebdae1fafff7d883448f
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname
              profileImgUrl: profileImgUrl