server:
  port: 8080
file:
  upload-dir: /tmp/uploads/
spring:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 100MB
  data:
    redis:
      host: 172.17.0.1
  mail:
    host: smtp.gmail.com
    port: 587
    username: GMAIL_ACCOUNT
    password: NEED_TO_INPUT_ON_SECRET
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    cache: false
    prefix: classpath:templates/
  datasource:
    url: jdbc:mariadb://172.17.0.1:3306/the_cupid_prod
    username: the-cupidlocal
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          kakao:
            scope:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.baseUrl}/{action}/oauth2/code/{registrationId}'
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
custom:
  site:
    name: The Cupid
    baseUrl: "http://118.67.142.168"

  genFile:
    dirPath: /tmp/uploads/