package com.sbs.apple.domain.user;

import com.sbs.apple.domain.board.Board;
import com.sbs.apple.domain.chat.ChatRoom;
import com.sbs.apple.domain.cybermoney.CyberMoneyTransaction;
import com.sbs.apple.domain.interest.Interest;
import com.sbs.apple.domain.notification.Notification;
import com.sbs.apple.domain.report.Report;
import lombok.Getter;
import lombok.Setter;

import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

@Getter@Setter
public class SiteUserDTO {
    private Integer id;
    private boolean userStop;
    private boolean userWarning;
    private String filename;
    private String filepath;
    private String username;
    private String password;
    private String nickname;
    private String gender;
    private int age;
    private String living;
    private List<String> hobbyList;
    private int tall;
    private String body_type;
    private String smoking;
    private String drinking;
    private List<String> styleList;
    private String religion;
    private String mbti;
    private String school;
    private String job;
    private String About_Me;
    private String desired_age;
    private String desired_hobby;
    private String desired_living;
    private String desired_tall;
    private String desired_body_type;
    private String desired_smoking;
    private String desired_drinking;
    private List<String> desired_styleList;
    private String desired_religion;
    private String desired_mbti;
    private String desired_school;
    private String desired_job;
    private List<Integer> chatRoomIds;
    private List<Integer> notificationIds;
    private List<Integer> interestIds;
    private List<Integer> reportIds;
    private int cyberMoney;
    private Integer receivedCyberMoney;
    private String role;
    private Set<UserRole> authorities;
    private List<Integer> boardIds;
    private List<CyberMoneyTransaction> receivedTransactions;
    private List<Long> completedTransactionIds;
    private Integer minHeart;

    public static SiteUserDTO fromEntity(SiteUser siteUser) {
        SiteUserDTO dto = new SiteUserDTO();
        dto.setId(siteUser.getId());
        dto.setUserStop(siteUser.isUserStop());
        dto.setUserWarning(siteUser.isUserWarning());
        dto.setFilename(siteUser.getFilename());
        dto.setFilepath(siteUser.getFilepath());
        dto.setUsername(siteUser.getUsername());
        dto.setPassword(siteUser.getPassword());
        dto.setNickname(siteUser.getNickname());
        dto.setGender(siteUser.getGender());
        dto.setAge(siteUser.getAge());
        dto.setLiving(siteUser.getLiving());
        dto.setHobbyList(siteUser.getHobbyList());
        dto.setTall(siteUser.getTall());
        dto.setBody_type(siteUser.getBody_type());
        dto.setSmoking(siteUser.getSmoking());
        dto.setDrinking(siteUser.getDrinking());
        dto.setStyleList(siteUser.getStyleList());
        dto.setReligion(siteUser.getReligion());
        dto.setMbti(siteUser.getMbti());
        dto.setSchool(siteUser.getSchool());
        dto.setJob(siteUser.getJob());
        dto.setAbout_Me(siteUser.getAbout_Me());
        dto.setDesired_age(siteUser.getDesired_age());
        dto.setDesired_hobby(siteUser.getDesired_hobby());
        dto.setDesired_living(siteUser.getDesired_living());
        dto.setDesired_tall(siteUser.getDesired_tall());
        dto.setDesired_body_type(siteUser.getDesired_body_type());
        dto.setDesired_smoking(siteUser.getDesired_smoking());
        dto.setDesired_drinking(siteUser.getDesired_drinking());
        dto.setDesired_styleList(siteUser.getDesired_styleList());
        dto.setDesired_religion(siteUser.getDesired_religion());
        dto.setDesired_mbti(siteUser.getDesired_mbti());
        dto.setDesired_school(siteUser.getDesired_school());
        dto.setDesired_job(siteUser.getDesired_job());
        dto.setChatRoomIds(siteUser.getChatRoomList().stream().map(ChatRoom::getId).collect(Collectors.toList()));
        dto.setNotificationIds(siteUser.getNotificationList().stream().map(Notification::getId).collect(Collectors.toList()));
        dto.setInterestIds(siteUser.getInterestList().stream().map(Interest::getId).collect(Collectors.toList()));
        dto.setReportIds(siteUser.getReportList().stream().map(Report::getId).collect(Collectors.toList()));
        dto.setCyberMoney(siteUser.getCyberMoney());
        dto.setReceivedCyberMoney(siteUser.getReceivedCyberMoney());
        dto.setRole(siteUser.getRole());
        dto.setAuthorities(siteUser.getAuthorities());
        dto.setBoardIds(siteUser.getBoardList().stream().map(Board::getId).collect(Collectors.toList()));
        dto.setReceivedTransactions(siteUser.getReceivedTransactions());
        dto.setCompletedTransactionIds(siteUser.getCompletedTransactions().stream().map(CyberMoneyTransaction::getId).collect(Collectors.toList()));
        dto.setMinHeart(siteUser.getMinHeart());
        return dto;
    }
}
